---
- name: "Backup zVirt VMs"
  hosts: localhost

  vars:
    engine_fqdn: zvirt.uruk.local
    engine_user: admin@internal
    engine_password: admin
    backup_count: 2
  roles:
    - zvirt_backup
