---
- name: "Backup zVirt VMs"
  hosts: localhost
  gather_facts: false

  vars_files:
    - backup_vars.yaml
  tasks:
    - include_tasks: tasks/serial.yaml
      when: not async_backup
    - include_tasks: tasks/async.yaml
      when: async_backup