---
- name: "Gather information about Export Storage Domain"
  ovirt.ovirt.ovirt_storage_domain_info:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ export_domain }}"
    follow:
      - vms
      - vms.disk_attachments
  register: export_domain_info
- name: "Set Export Storage Domain Host as variable"
  set_fact:
    export_domain_host: "{{ export_domain_info.ovirt_storage_domains[0].storage.address }}"

- name: "Find all backups"
  set_fact:
    all_backups: "{{ export_domain_info | json_query(query) }}"
  vars:
    query: "ovirt_storage_domains[0].vms[*].{name:name,id:id,disks:disk_attachments[*].id}"

- name: "Define relevant backups"
  set_fact:
    relevant_backups: "{{ all_backups | json_query(query) | select('match', regex) | list }}"
  vars:
    query: "[*].name"
    regex: "^{{ vm }}-temp-backup.*"
