---
- name: "Create {{ vm }} snapshot"
  ovirt.ovirt.ovirt_snapshot:
    auth: "{{ ovirt_auth }}"
    vm_name: "{{ vm }}"
    description: "{{ vm }}_{{ vm_id[-4:] }}_MB_{{ backup_date_format }}"
    timeout: "{{ backup_timeout }}"
  register: vm_snapshot
- name: "Clone temporal VM from {{ vm }} snapshot"
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    snapshot_vm: "{{ vm }}"
    snapshot_name: "{{ vm }}_{{ vm_id[-4:] }}_MB_{{ backup_date_format }}"
    name: "{{ vm }}_{{ vm_id[-4:] }}_MB_{{ backup_date_format }}"
    state: present
    timeout: "{{ backup_timeout }}"
- name: "Export {{ vm }} clone to Export Storage Domain"
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    name: "{{ vm }}_{{ vm_id[-4:] }}_MB_{{ backup_date_format }}"
    state: exported
    export_domain: "{{ export_domain }}"
    timeout: "{{ backup_timeout }}"
- name: "Remove temporal VM"
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    name: "{{ vm }}_{{ vm_id[-4:] }}_MB_{{ backup_date_format }}"
    state: absent
- name: "Remove {{ vm }} snapshot"
  ovirt_snapshot:
    auth: "{{ ovirt_auth }}"
    state: absent
    vm_name: "{{ vm }}"
    snapshot_id: "{{ vm_snapshot.snapshot.id }}"
