---
- setup:
- name: "Login into zVirt API"
  ovirt.ovirt.ovirt_auth:
    hostname: "{{ engine_fqdn }}"
    username: "{{ engine_user }}"
    password: "{{ engine_password }}"

- block:
    - name: "Import info collector tasklist"
      import_tasks: backup_info.yaml
    - name: "Check for {{ vm }} stale backups"
      fail:
        msg: "There are {{ relevant_backups | length }} backups, while {{ backup_count }} backups required. Removing stale backups"
      when: (relevant_backups | length) >= backup_count
    - name: "Include backup creation tasklist"
      include_tasks: create_backup.yaml
  rescue:
    - name: "Loop stale backup removal tasklist"
      include_tasks: remove_stale_backups.yaml
      loop: "{{ range(0, (relevant_backups | length - backup_count + 1)) | list }}"
    - name: "Include backup creation tasklist"
      include_tasks: create_backup.yaml
  always:
    - name: "Logout from zVirt API"
      ovirt.ovirt.ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
