---
- name: "Gather facts for ansible_date_time"
  setup:
- name: "Login"
  ovirt.ovirt.ovirt_auth:
    hostname: "{{ engine_fqdn }}"
    username: "{{ engine_user }}"
    password: "{{ engine_password }}"
- block:
    - import_tasks: async.yaml
      when: async_backup
    - import_tasks: sequential.yaml
      when: not async_backup
  always:
    - name: "Logout"
      ovirt.ovirt.ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
