---
- name: "Gather facts for ansible_date_time"
  setup:

- name: "Login"
  ovirt.ovirt.ovirt_auth:
    hostname: "{{ engine_fqdn }}"
    username: "{{ engine_user }}"
    password: "{{ engine_password }}"

- block:
    - name: "Find export domain if not specified"
      block:
        - name: "Gather Facts about domains"
          ovirt.ovirt.ovirt_storage_domain_info:
            auth: "{{ ovirt_auth }}"
            pattern: name=*
          register: sd_info
        - name: "Set export storage domain name"
          set_fact:
            export_domain: "{{ sd_info | json_query(query) | selectattr('type', '==', 'export') | map(attribute='name') | first }}"
          vars:
            query: "ovirt_storage_domains[*]"
      rescue:
        - fail:
            msg: "Export domain doesn't exist"

    - name: "Backing Up"
      include_tasks: backup.yaml
  when: async_backup
  always:
    - name: "Logout"
      ovirt.ovirt.ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent

- block:
    - name: "Find export domain if not specified"
      block:
        - name: "Gather Facts about domains"
          ovirt.ovirt.ovirt_storage_domain_info:
            auth: "{{ ovirt_auth }}"
            pattern: name=*
          register: sd_info
        - name: "Set export storage domain name"
          set_fact:
            export_domain: "{{ sd_info | json_query(query) | selectattr('type', '==', 'export') | map(attribute='name') | first }}"
          vars:
            query: "ovirt_storage_domains[*]"
      rescue:
        - fail:
            msg: "Export domain doesn't exist"

    - name: "Backing Up"
      include_tasks: backup.yaml
      loop: "{{ vms_to_backup }}"
      loop_control:
        loop_var: vm
  when: not async_backup
  always:
    - name: "Logout"
      ovirt.ovirt.ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
