---
- setup:
- name: "Login"
  ovirt.ovirt.ovirt_auth:
    hostname: "{{ engine_fqdn }}"
    username: "{{ engine_user }}"
    password: "{{ engine_password }}"
- block:
    - name: "Gather list of VMs to backup"
      ovirt_vm_info:
        auth: "{{ ovirt_auth }}"
        pattern: "tag=backup_{{ ansible_date_time['weekday'] }}"
      register: vms_list
    - set_fact:
        vms_to_backup: "{{ vms_list | json_query('ovirt_vms[*].name') | list }}"
  always:
    - name: "Logout"
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent

- block:
    - name: "start backup"
      shell: "ansible-playbook tasks/backup.yaml -e 'vm={{ item }}' -e 'async_backup=true'"
      async: 7200
      poll: 0
      loop: "{{ vms_to_backup }}"
      register: backup_status
    - name: "Wait for finish"
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: jobs
      until: jobs.finished
      retries: 320
      delay: 20
      loop: "{{ backup_status.results }}"
  when: vms_to_backup | length > 0
