---
- block:
    - name: "Gather info about export domain"
      ovirt.ovirt.ovirt_storage_domain_info:
        auth: "{{ ovirt_auth }}"
        pattern: "name={{ export_domain }}"
        follow:
          - vms
          - vms.disk_attachments
      register: export_domain_info
    - name: "Set Export Domain Host"
      set_fact:
        export_domain_host: "{{ export_domain_info.ovirt_storage_domains[0].storage.address }}"
    - debug:
        msg: "Export domain host is '{{ export_domain_host}}'"
      tags:
        - never
        - debug

    - name: "Find all backups"
      set_fact:
        all_backups: "{{ export_domain_info | json_query(query) }}"
      vars:
        query: "ovirt_storage_domains[0].vms[*].{name:name,id:id,disks:disk_attachments[*].id}"
    - debug:
        msg: "Total number of backups is {{ all_backups | length }}"

    - name: "Find relevant backups"
      set_fact:
        relevant_backups: "{{ all_backups | json_query(query) | select('match', regex) | list }}"
      vars:
        query: "[*].name"
        regex: "^{{ vm }}-temp-backup.*"
    - debug:
        msg: "{{ vm }} has {{ relevant_backups | length }} backups, {{ (range(0, (relevant_backups | length - backup_count + 1))) | first | int + 1 }} stale backups will be removed"
      tags:
        - never
        - debug
  tags:
    - always
